"""empty message

Revision ID: 9d5fe8796a3a
Revises: 79fe88550509
Create Date: 2024-02-20 16:51:20.561259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d5fe8796a3a'
down_revision = '79fe88550509'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_duplicate',
    sa.Column('path', sa.String(length=512), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('dup_asset_id', sa.Integer(), nullable=True),
    sa.Column('dup_kind', sa.String(length=50), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('path')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('asset_duplicate')
    # ### end Alembic commands ###
